```{r {{id}}-subset}
if (interactive()) {
  this_id <- sample(trend$id, 1)
} else {
  this_id <- "{{id}}"
}
trend %>%
  distinct(id, species) %>%
  filter(id == this_id) -> this
predictions %>%
  filter(species == this$species) -> this_predictions
trend %>%
  filter(
    species %in% c(this$species, "Harm_axyr")
  ) %>%
  mutate(
    species = factor(species) %>%
      relevel(this$species)
  ) -> this_trend
lincomb %>%
  filter(species == this$species) %>%
  mutate(
    species = factor(species) %>%
      relevel(this$species)
  ) -> this_lincomb
man_col <- c(rev(traffic_palette(7)), "grey75", "grey25", "grey50")
man_col[4] <- inbo_steun_blauw
names(man_col) <- levels(this_predictions$presence)
man_col2 <- c(rev(traffic_palette(3)), "grey50")
man_col2[2] <- inbo_steun_blauw
names(man_col2) <- levels(this_predictions$presence2)
```

## `r this$species`

### Average probability of occurrence

We use only the global average $\beta_0$, the second order random walk $b_t$ and the monitoring effect $E_{tx}$.
We fix the monitoring effort at 4 days per year per location (the median value in the data).

```{r {{id}}-base}
this_trend %>%
  ggplot(aes(x = year, y = mean, ymin = lcl, ymax = ucl)) +
  geom_ribbon(
    aes(fill = country, group = interaction(species, country)),
    alpha = 0.3, linetype = 3
  ) +
  geom_line(aes(colour = country, linetype = species)) +
  scale_y_continuous(labels = percent, limits = 0:1) +
  theme(axis.title = element_blank())
```

```{r {{id}}-trend-compare, eval = this$species != "Harm_axyr"}
this_trend %>%
  transmute(
    species = ifelse(species == "Harm_axyr", "ref", "current"),
    median, year, lcl, ucl, country
  ) %>%
  pivot_wider(names_from = species, values_from = c(median, lcl, ucl)) %>%
  arrange(year) %>%
  group_by(country) %>%
  mutate(
    ref2 = lead(median_ref),
    current2 = lead(median_current)
  ) -> trend_compare
trend_compare %>%
  filter(!is.na(median_ref), !is.na(ref2)) %>%
  ggplot(
    aes(
      x = median_ref, xend = ref2, y = median_current, yend = current2,
      colour = country
    )
  ) +
  geom_abline(linetype = 2) +
  geom_segment(arrow = arrow(length = unit(2, "mm"))) +
  scale_x_continuous("occurrence H. axiridis", labels = percent) +
  scale_y_continuous(paste("occurrence", this$species), labels = percent)
```

### Short term linear trends

```{r {{id}}-change}
this_lincomb %>%
  ggplot(aes(x = center, y = median, ymin = lcl, ymax = ucl)) +
  geom_hline(yintercept = 0, linetype = 2) +
  geom_hline(yintercept = thresholds, linetype = 3) +
  geom_ribbon(alpha = 0.3, aes(fill = duration)) +
  geom_line(aes(colour = duration)) +
  scale_y_continuous(
    "trend on logit scale",
    sec.axis = sec_axis(exp, "odds ratio")
  ) +
  theme(axis.title.x = element_blank()) +
  facet_wrap(~country)
```

```{r {{id}}-change-ha-02}
this_lincomb %>%
  filter(duration == "2") %>%
  ggplot(aes(x = center, y = median, ymin = lcl, ymax = ucl)) +
  geom_hline(yintercept = 0, linetype = 2) +
  geom_hline(yintercept = thresholds, linetype = 3) +
  geom_ribbon(alpha = 0.3, aes(fill = country)) +
  geom_point(size = 5, aes(colour = change), show.legend = FALSE) +
  geom_text(aes(label = change), show.legend = FALSE, colour = "white") +
  scale_colour_manual(values = man_colt) +
  scale_y_continuous(
    "trend on logit scale",
    sec.axis = sec_axis(exp, "odds ratio")
  ) +
  theme(axis.title.x = element_blank()) +
  ggtitle(paste("2 year trends", this$species))
```

```{r {{id}}-change-ha-05}
this_lincomb %>%
  filter(duration == "5") %>%
  ggplot(aes(x = center, y = median, ymin = lcl, ymax = ucl)) +
  geom_hline(yintercept = 0, linetype = 2) +
  geom_hline(yintercept = thresholds, linetype = 3) +
  geom_ribbon(alpha = 0.3, aes(fill = country)) +
  geom_point(size = 5, aes(colour = change), show.legend = FALSE) +
  geom_text(aes(label = change), show.legend = FALSE, colour = "white") +
  scale_colour_manual(values = man_colt) +
  scale_y_continuous(
    "trend on logit scale",
    sec.axis = sec_axis(exp, "odds ratio")
  ) +
  theme(axis.title.x = element_blank()) +
  ggtitle(paste("5 year trends", this$species))
```

```{r {{id}}-change-ha-10}
this_lincomb %>%
  filter(duration == "10") %>%
  ggplot(aes(x = center, y = median, ymin = lcl, ymax = ucl)) +
  geom_hline(yintercept = 0, linetype = 2) +
  geom_hline(yintercept = thresholds, linetype = 3) +
  geom_ribbon(alpha = 0.3, aes(fill = country)) +
  geom_point(size = 5, aes(colour = change), show.legend = FALSE) +
  geom_text(aes(label = change), show.legend = FALSE, colour = "white") +
  scale_colour_manual(values = man_colt) +
  scale_y_continuous(
    "trend on logit scale",
    sec.axis = sec_axis(exp, "odds ratio")
  ) +
  theme(axis.title.x = element_blank()) +
  ggtitle(paste("10 year trends", this$species))
```

### Predicted maps

#### Median of prediction occurrence probability

```{r {{id}}-map, eval = any(this_predictions$year <= 1997), fig.height=3}
this_predictions %>%
  filter(year <= 1997) %>%
  ggplot(aes(fill = median)) +
  geom_sf(colour = NA) +
  facet_wrap(~year, nrow = 2) +
  theme_map() +
  scale_fill_gradientn(colours = traffic_palette(5), limits = 0:1) +
  theme(strip.text = element_text(size = rel(0.5)))
```

```{r {{id}}-map-2, fig.height=3}
this_predictions %>%
  filter(1997 < year, year <= 2005) %>%
  ggplot(aes(fill = median)) +
  geom_sf(colour = NA) +
  facet_wrap(~year, nrow = 2) +
  theme_map() +
  scale_fill_gradientn(colours = traffic_palette(5), limits = 0:1) +
  theme(strip.text = element_text(size = rel(0.5)))
```

```{r {{id}}-map3, fig.height=3}
this_predictions %>%
  filter(2005 < year, year <= 2013) %>%
  ggplot(aes(fill = median)) +
  geom_sf(colour = NA) +
  facet_wrap(~year, nrow = 2) +
  theme_map() +
  scale_fill_gradientn(colours = traffic_palette(5), limits = 0:1) +
  theme(strip.text = element_text(size = rel(0.5)))
```

```{r {{id}}-map4, fig.height=3}
this_predictions %>%
  filter(2013 < year) %>%
  ggplot(aes(fill = median)) +
  geom_sf(colour = NA) +
  facet_wrap(~year, nrow = 2) +
  theme_map() +
  scale_fill_gradientn(colours = traffic_palette(5), limits = 0:1) +
  theme(strip.text = element_text(size = rel(0.5)))
```

#### 10 class precence

```{r {{id}}-map-presence, eval = any(this_predictions$year <= 1997), fig.height=3}
this_predictions %>%
  filter(year <= 1997) %>%
  ggplot(aes(fill = presence)) +
  geom_sf(colour = NA) +
  facet_wrap(~year, nrow = 2) +
  theme_map() +
  scale_fill_manual(values = man_col, drop = FALSE) +
  ggtitle(paste("10 class presence", this$species)) +
  theme(strip.text = element_text(size = rel(0.5)))
```

```{r {{id}}-map-presence-2, fig.height=3}
this_predictions %>%
  filter(1997 < year, year <= 2005) %>%
  ggplot(aes(fill = presence)) +
  geom_sf(colour = NA) +
  facet_wrap(~year, nrow = 2) +
  theme_map() +
  scale_fill_manual(values = man_col, drop = FALSE) +
  ggtitle(paste("10 class presence", this$species)) +
  theme(strip.text = element_text(size = rel(0.5)))
```

```{r {{id}}-map-presence-3, fig.height=3}
this_predictions %>%
  filter(2005 < year, year <= 2013) %>%
  ggplot(aes(fill = presence)) +
  geom_sf(colour = NA) +
  facet_wrap(~year, nrow = 2) +
  theme_map() +
  scale_fill_manual(values = man_col, drop = FALSE) +
  ggtitle(paste("10 class presence", this$species)) +
  theme(strip.text = element_text(size = rel(0.5)))
```

```{r {{id}}-map-presence-4, fig.height=3}
this_predictions %>%
  filter(2013 < year) %>%
  ggplot(aes(fill = presence)) +
  geom_sf(colour = NA) +
  facet_wrap(~year, nrow = 2) +
  theme_map() +
  scale_fill_manual(values = man_col, drop = FALSE) +
  ggtitle(paste("10 class presence", this$species)) +
  theme(strip.text = element_text(size = rel(0.5)))
```

#### 4 class precence

```{r {{id}}-map-presence2, eval = any(this_predictions$year <= 1997), fig.height=3}
this_predictions %>%
  filter(year <= 1997) %>%
  ggplot(aes(fill = presence2)) +
  geom_sf(colour = NA) +
  facet_wrap(~year, nrow = 2) +
  theme_map() +
  scale_fill_manual("presence", values = man_col2, drop = FALSE) +
  ggtitle(paste("4 class presence", this$species)) +
  theme(strip.text = element_text(size = rel(0.5)))
```

```{r {{id}}-map-presence2-2, fig.height=3}
this_predictions %>%
  filter(1997 < year, year <= 2005) %>%
  ggplot(aes(fill = presence2)) +
  geom_sf(colour = NA) +
  facet_wrap(~year, nrow = 2) +
  theme_map() +
  scale_fill_manual("presence", values = man_col2, drop = FALSE) +
  ggtitle(paste("4 class presence", this$species)) +
  theme(strip.text = element_text(size = rel(0.5)))
```

```{r {{id}}-map-presence2-3, fig.height=3}
this_predictions %>%
  filter(2005 < year, year <= 2013) %>%
  ggplot(aes(fill = presence2)) +
  geom_sf(colour = NA) +
  facet_wrap(~year, nrow = 2) +
  theme_map() +
  scale_fill_manual("presence", values = man_col2, drop = FALSE) +
  ggtitle(paste("4 class presence", this$species)) +
  theme(strip.text = element_text(size = rel(0.5)))
```

```{r {{id}}-map-presence2-4, fig.height=3}
this_predictions %>%
  filter(2013 < year) %>%
  ggplot(aes(fill = presence2)) +
  geom_sf(colour = NA) +
  facet_wrap(~year, nrow = 2) +
  theme_map() +
  scale_fill_manual("presence", values = man_col2, drop = FALSE) +
  ggtitle(paste("4 class presence", this$species)) +
  theme(strip.text = element_text(size = rel(0.5)))
```
