---
title: "Results"
author: "Thierry Onkelinx"
date: "8-3-2021"
output: html_document
params:
  models:
    label: "Select a base model"
    value: "../../Analysis/models/base/harm_axyr_1000_3.rds"
    input: file
---

```{r setup, include=FALSE}
library(knitr)
opts_chunk$set(echo = FALSE)
library(ladybird)
library(tidyverse)
library(plotly)
library(scales)
library(INBOtheme)
```

```{r load-base-models}
dirname(params$models) %>%
  list.files(full.names = TRUE) %>%
  map(readRDS) -> base_models
species <- map_chr(base_models, "species")
map(base_models, "hyperpar") %>%
  map(rownames_to_column, var = "parameter") %>%
  map2(species, ~mutate(.x, species = .y)) %>%
  bind_rows() %>%
  mutate(model = "base") -> hyperpar
map(base_models, "trend") %>%
  map2(species, ~mutate(.x, species = .y)) %>%
  bind_rows() %>%
  mutate(model = "base") -> trend
trend %>%
  filter(species != "Harm_axyr") %>%
  group_by(species) %>%
  slice_max(year, n = 1) %>%
  ungroup() %>%
  slice_max(mean, prop = 0.5) %>%
  pull(species) -> top_species
```

```{r load-secondary-models}
dirname(params$models) %>%
  file.path("..", "secondary") %>%
  list.files(full.names = TRUE) %>%
  map(readRDS) -> secondary_models
sec_species <- map_chr(secondary_models, "species")
map(secondary_models, "fixed") %>%
  map(rownames_to_column, var = "parameter") %>%
  map2(sec_species, ~mutate(.x, species = .y)) %>%
  bind_rows() -> sec_fixed
map(secondary_models, "hyperpar") %>%
  map(rownames_to_column, var = "parameter") %>%
  map2(sec_species, ~mutate(.x, species = .y)) %>%
  bind_rows() %>%
  mutate(model = "secondary") -> sec_hyperpar
map(secondary_models, "trend") %>%
  map2(sec_species, ~mutate(.x, species = .y)) %>%
  bind_rows() %>%
  mutate(model = "secondary") -> sec_trend
sec_trend %>%
  filter(type == "median") %>%
  group_by(species) %>%
  slice_max(year, n = 1) %>%
  ungroup() %>%
  slice_max(mean, prop = 0.5) %>%
  pull(species) -> sec_top_species
```

```{r combined}
trend %>%
  mutate(type = "") %>%
  bind_rows(sec_trend) %>%
  mutate(prediction = interaction(model, type, sep = " ")) -> all_trend
hyperpar %>%
  bind_rows(sec_hyperpar) -> all_hyperpar
```

# Interactions with _H. axyridis_

```{r sec-fixed, fig.cap = "Parameter estimate when using the (logit) predicted occurrence of H. axyridis as fixed effect covariate."}
sec_fixed %>%
  filter(parameter == "secondary") %>%
  mutate(species = reorder(species, mean)) %>%
  ggplot(aes(x = mean, xmin = `0.025quant`, xmax = `0.975quant`, y = species)) +
  geom_vline(xintercept = 0, linetype = 2) +
  geom_errorbarh() +
  geom_point() +
  theme(axis.title = element_blank())
```

## General trends

```{r trends-adal-bipu}
plot_trend <- function(this_species) {
  all_trend %>%
    filter(species  == this_species, type %in% c("median", "without", "")) %>%
    ggplot(aes(x = year, y = mean, ymin = lcl, ymax = ucl)) +
    geom_ribbon(aes(fill = prediction, colour = prediction), alpha = 0.3, linetype = 3) +
    geom_line(aes(colour = prediction)) +
    scale_y_continuous(labels = percent, limits = c(0, 1)) +
    theme(axis.title = element_blank()) +
    ggtitle(this_species)
}
plot_trend("Adal_bipu")
```
```{r trends-adal-dece}
plot_trend("Adal_dece")
```

```{r trends-calv-dece}
plot_trend("Calv_dece")
```

```{r trends-calv-quat}
plot_trend("Calv_quat")
```

```{r trends-cocc-sept}
plot_trend("Cocc_sept")
```


```{r trends-cocc-quin}
plot_trend("Cocc_quin")
```

```{r trends-exoc-quad}
plot_trend("Exoc_quad")
```

```{r trends-haly-sede}
plot_trend("Haly_sede")
```

```{r trends-harm-axyr}
plot_trend("Harm_axyr")
```

```{r trends-harm-quad}
plot_trend("Harm_quad")
```

```{r trends-hipp_vari}
plot_trend("Hipp_vari")
```

```{r trends-oeno-cong}
plot_trend("Oeno_cong")
```

```{r trends-prop-quat}
plot_trend("Prop_quat")
```

```{r trends-psyl-vigi}
plot_trend("Psyl_vigi")
```

```{r trends-tytt-sede}
plot_trend("Tytt_sede")
```

## Spatio-temporal fields

```{r sec-range}
all_hyperpar %>%
  filter(parameter == "Range for site") %>%
  mutate(species = reorder(species, mean)) %>%
  ggplot(
    aes(
      x = mean, xmin = `0.025quant`, xmax = `0.975quant`, y = species,
      colour = model
    )
  ) +
  geom_errorbarh(position = position_dodge(width = 0.5)) +
  geom_point(position = position_dodge(width = 0.5)) +
  scale_x_continuous(limits = c(0, NA)) +
  ggtitle("Range of the spatio-temporal field in km") +
  theme(axis.title = element_blank())
```

```{r sec-stdev}
all_hyperpar %>%
  filter(parameter == "Stdev for site") %>%
  mutate(species = reorder(species, mean)) %>%
  ggplot(
    aes(
      x = mean, xmin = `0.025quant`, xmax = `0.975quant`, y = species,
      colour = model
    )
  ) +
  geom_errorbarh(position = position_dodge(width = 0.5)) +
  geom_point(position = position_dodge(width = 0.5)) +
  scale_x_continuous(limits = c(0, NA)) +
  ggtitle("Stdev of the spatio-temporal field in km") +
  theme(axis.title = element_blank())
```

```{r sec-rho}
all_hyperpar %>%
  filter(parameter == "GroupRho for site") %>%
  mutate(species = reorder(species, mean)) %>%
  ggplot(
    aes(
      x = mean, xmin = `0.025quant`, xmax = `0.975quant`, y = species,
      colour = model
    )
  ) +
  geom_errorbarh(position = position_dodge(width = 0.5)) +
  geom_point(position = position_dodge(width = 0.5)) +
  ggtitle("Rho of the spatio-temporal field in km") +
  theme(axis.title = element_blank())
```
